BLUEPRINT_PATH = "./assets/blueprint.png"
BLUEPRINT_OFFSET = (700, 8300)
BOX_SIZE = 30
BORDER = 0
FONT_PATH = "./assets/default-font.ttf"
FONT_SIZE = 180
FONT_COLOR = (0, 0, 0)
FINAL_NAME = "NALAZ_{}_{}.png"
REQUIRED_DIRS = ["./assets/qrs", "./results"]
